name: Trigger auto deployment for fair-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main-upstream ]
    paths:
    - '**'
    - '.github/workflows/fair-backend-AutoDeployTrigger-ebf973fb-6104-45c2-8693-c97c2d1a1e34.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.FAIRBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FAIRBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FAIRBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: fairacr.azurecr.io
          registryUsername: ${{ secrets.FAIRBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FAIRBACKEND_REGISTRY_PASSWORD }}
          containerAppName: backend2
          resourceGroup: SH-DCR-FAIR-Dev-RG
          imageToBuild: fairacr.azurecr.io/fair-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_



